name: CI SupraShare

on: [push, pull_request]

jobs:

  qa:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pre-commit/action@v2.0.2

  test:
    needs: qa
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Micromamba setup
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-env: true
          micromamba-version: 0.24.0
          environment-name: c60-cage-data

      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest -v 

  publish:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get image metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
